@baseUrl = http://localhost:3000/v1
@pattern = vehicle-models

### AUTH: Get
GET {{baseUrl}}/{{pattern}}

### AUTH: Get by id
GET {{baseUrl}}/{{pattern}}/2

### ADMIN: Create
POST {{baseUrl}}/{{pattern}}

{
  "seriesName":"6-series",
  "commercialName":"640GT",
  "modelYear":2018,
  "brandId":1,
  "engineDisplacement":2000,
  "driveType":"rwd",
  "fuelType":"gasoline",
  "bodyStyle":"gt",
  "transmissionType":"automatic"
}

### ADMIN: Update

PUT {{baseUrl}}/{{pattern}}/4

{
  "seriesName":"3-series",
  "commercialName":"320GT",
  "modelYear":2015,
  "engineDisplacement":2000,
  "driveType":"rwd",
  "fuelType":"gasoline",
  "bodyStyle":"gt",
  "transmissionType":"manual"
}

### ADMIN: Delete
DELETE {{baseUrl}}/{{pattern}}/1