@baseUrl = http://localhost:3000/v1
@pattern = brand-series

### AUTH: Get
GET {{baseUrl}}/{{pattern}}

### AUTH: Get by id
GET {{baseUrl}}/{{pattern}}/1

### ADMIN: Create
POST {{baseUrl}}/{{pattern}}

{
  "name":"3-series",
  "brandID":1
}

### ADMIN: Update

PUT {{baseUrl}}/{{pattern}}/1

{
  "name":"3-series",
  "brandID":1
}


### ADMIN: Delete
DELETE {{baseUrl}}/{{pattern}}/1