DROP MATERIALIZED VIEW IF EXISTS m_v_towns CASCADE;
DROP INDEX IF EXISTS idx2_m_v_towns_city_id CASCADE;
DROP INDEX IF EXISTS idx_m_v_towns_city_id CASCADE;
DROP TABLE IF EXISTS city_towns CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TYPE IF EXISTS regions CASCADE;
