
DROP TABLE IF EXISTS series_models CASCADE;
DROP TYPE IF EXISTS engine_types CASCADE;
DROP TYPE IF EXISTS transmission_types CASCADE;
DROP TYPE IF EXISTS body_styles CASCADE;
DROP TYPE IF EXISTS fuel_types CASCADE;
DROP TYPE IF EXISTS drive_types CASCADE;