@baseUrl = http://localhost:3000/v1
@pattern = brands

### AUTH: Get
GET {{baseUrl}}/{{pattern}}

### AUTH: Get by id
GET {{baseUrl}}/{{pattern}}/1

### ADMIN: Create
POST {{baseUrl}}/{{pattern}}

{
  "name":"BMW",
  "logo":"MockFile1.png"
}

### ADMIN: Update

PUT {{baseUrl}}/{{pattern}}/1

{
  "logo":"MockFile2.png"
}

### ADMIN: Delete
DELETE {{baseUrl}}/{{pattern}}/1