cat << EOF

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS tablefunc;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgaudit;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE ROLE "${PROJECT_ID}_admin";

GRANT CONNECT ON DATABASE "${PROJECT_ID}-db" TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON SCHEMA public TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO "${PROJECT_ID}_admin";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${PROJECT_ID}_admin";

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "${PROJECT_ID}_admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "${PROJECT_ID}_admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO "${PROJECT_ID}_admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "${PROJECT_ID}_admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TYPES TO "${PROJECT_ID}_admin";

GRANT "${PROJECT_ID}_admin" TO "devops@$PROJECT_ID.iam";

EOF